### ISSUE TITLE
Hangs for dyndns

### ISSUE THREAD

**Issue by lattice0** [theonemule/docker-dynamic-dns#3]
I tried the docker and the script alone, and in both cases it just hangs, it never prints any output after it outputs the url it is calling. Do you know what could be the problem?

**Comment by lattice0** [comment]
ps: if I put that URL in the browser, it works and updates my IP, so there's no problem with my input

**Comment by theonemule** [comment]
Does the container have any output? Can I see that?

**Comment by lattice0** [comment]
```
USER=XXXXXXXX PASSWORD=XXXXXXXXXX SERVICE=dyndns HOSTNAME=XXXXXXXX.dyndns.org DETECTIP=1 INTERVAL=3 /home/pi/no-ip.sh
--header="Authorization: IiRVU0VSOiRQQVNTV09SRCIK" --user-agent="no-ip shell script/1.0 mail@mail.com" https://XXXXXXX:XXXXXXX@members.dyndns.org/v3/update?hostname=XXXXXXXX.dyndns.org&myip=XXXXXXXXXXXXX
```

**Comment by sh99** [comment]
Did you make any progress with this issue, I have what I believe is the same problem, zero response being recorded from DynDNS ?

This is from the container log output:

--header="Authorization:&nbsp;IiRVU0VSOiRQQVNTV09SRCIK"&nbsp;--user-agent="no-ip&nbsp;shell&nbsp;script/1.0&nbsp;mail@mail.com"&nbsp;https://XXXXXXX:XXXXXXX@members.dyndns.org/v3/update?hostname=XXXXXXXXXX.dnsalias.com&amp;myip=XXX.XXX.XXX.XXX

**Comment by CushItRealGood** [comment]
I remember running into this issue on my fork. I think it had something to do with $USER:$PASSWORD getting passed literally.
If you run this in ubuntu:
```
$(echo '"$USER:$PASSWORD"' | base64)
```
you get the following:
```
IiRVU0VSOiRQQVNTV09SRCIK: command not found
```
