### ISSUE TITLE
Question: Successful configuration

### ISSUE THREAD

**Issue by mbierman** [theonemule/docker-dynamic-dns#9]
How do I see in my docker logs if it has worked? It would be nice if there was a message to indicate a successful connection to noip so I don't have to wait a month to see if it worked.

**Comment by Animal-UK** [comment]
> How do I see in my docker logs if it has worked? It would be nice if there was a message to indicate a successful connection to noip so I don't have to wait a month to see if it worked.

you can see if its updated in the noip portal
